# Generated by Django 5.1.6 on 2025-02-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointments',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
